# Generated by Django 4.2.5 on 2023-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalparticipant',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='finalparticipant',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='chosen_topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='judge',
            name='group_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='final_1tour_score',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='order_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
