# Generated by Django 4.2.5 on 2023-09-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.SmallIntegerField(blank=True, default=1)),
                ('description', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.criteria', to_field='description')),
            ],
        ),
        migrations.DeleteModel(
            name='BigJudge',
        ),
        migrations.DeleteModel(
            name='FinalParticipant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_final',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_1criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_2criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_3criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_4criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_5criteria',
        ),
        migrations.AddField(
            model_name='participant',
            name='chosen_topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='judge',
            name='group_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='final_1tour_score',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='order_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.judge'),
        ),
        migrations.AddField(
            model_name='voting',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.participant'),
        ),
    ]
