# Generated by Django 4.2.5 on 2023-09-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_criteria_voting_delete_bigjudge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='code_for_link',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_id',
        ),
    ]
