# Generated by Django 4.2.5 on 2023-09-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_finalparticipant_city_finalparticipant_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1tour_1criteria', models.SmallIntegerField(blank=True, default=0)),
                ('score_1tour_2criteria', models.SmallIntegerField(blank=True, default=0)),
                ('score_1tour_3criteria', models.SmallIntegerField(blank=True, default=0)),
                ('score_1tour_4criteria', models.SmallIntegerField(blank=True, default=0)),
                ('score_1tour_5criteria', models.SmallIntegerField(blank=True, default=0)),
                ('personal_judge_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voting.judge', to_field='code_for_link')),
                ('personal_participant_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voting.participant', to_field='code_for_link')),
            ],
        ),
        migrations.DeleteModel(
            name='BigJudge',
        ),
        migrations.DeleteModel(
            name='FinalParticipant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_1criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_2criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_3criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_4criteria',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='score_1tour_5criteria',
        ),
    ]
