# Generated by Django 4.2.5 on 2023-09-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_participant_previous_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='criteria',
        ),
    ]
